'use client';
import {useEffect,useState} from 'react';
import {MapPin,Users,ExternalLink,Info,Search} from 'lucide-react';
import type {Poll} from '@/lib/tse';
const codes:Record<string,string>={'11':'RO','12':'AC','13':'AM','14':'RR','15':'PA','16':'AP','17':'TO','21':'MA','22':'PI','23':'CE','24':'RN','25':'PB','26':'PE','27':'AL','28':'SE','29':'BA','31':'MG','32':'ES','33':'RJ','35':'SP','41':'PR','42':'SC','43':'RS','50':'MS','51':'MT','52':'GO','53':'DF'};
const centers:Record<string,number[]>={AC:[-70.5,-9.4],AM:[-64,-4.2],RR:[-61.4,2.1],RO:[-63,-11],PA:[-53,-4],AP:[-51.8,1.4],TO:[-48.2,-10.4],MA:[-45,-5.2],PI:[-42.6,-8],CE:[-39.5,-5],RN:[-36.6,-5.6],PB:[-36.6,-7.1],PE:[-38,-8.5],AL:[-36.4,-9.7],SE:[-37.3,-10.8],BA:[-41.6,-12.7],MT:[-56,-13],GO:[-49.6,-16.4],DF:[-47.5,-15.5],MS:[-54.6,-20.5],MG:[-44.5,-18.7],ES:[-40.5,-19.6],RJ:[-42.2,-22.2],SP:[-48.8,-22.1],PR:[-51.7,-24.7],SC:[-50.4,-27.3],RS:[-53,-30.2]};
type Candidate={id:string;name:string;fullName:string;number:string;party:string;partyName:string;uf:string;office:string;turn:string;election:string;status:string;coalition:string;composition:string};
function project(p:number[]){return [(p[0]+75)*13.2,(6-p[1])*13.2]}
function path(geometry:any){const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates;return polygons.map((poly:number[][][])=>poly.map(ring=>ring.map((p,i)=>{const [x,y]=project(p);return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')+'Z').join(' ')).join(' ')}
export default function ElectoralMap({year,records,nationalRecords,uf,office,onUf,onOffice,showMap=true,asset}:{year:number;records:Poll[];nationalRecords:Poll[];uf:string;office:string;onUf:(s:string)=>void;onOffice:(s:string)=>void;showMap?:boolean;asset:(s:string)=>string}){
 const [features,setFeatures]=useState<any[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[generated,setGenerated]=useState(''),[party,setParty]=useState(''),[search,setSearch]=useState(''),[turn,setTurn]=useState('1'),[status,setStatus]=useState(''),[hover,setHover]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(''),[mapError,setMapError]=useState(''),[limit,setLimit]=useState(12);
 useEffect(()=>{fetch(asset('/maps/brazil-states.geojson')).then(r=>r.json()).then((d:any)=>setFeatures(d.features)).catch(()=>setMapError('Não foi possível carregar o mapa.'))},[]);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');setCandidates([]);setParty('');setStatus('');setLimit(12);if(![2026,2022,2018,2014].includes(year)){setBusy(false);return}fetch(asset(`/data/candidates-${year}.json`),{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('Cadastro de candidatos indisponível.');return r.json()}).then((d:any)=>{setCandidates(d.records);setGenerated(d.generated)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[year]);
 const scope=candidates.filter(r=>r.office===office&&(!uf||uf==='BR'||office==='Presidente'||r.uf===uf)&&r.turn===turn);
 const parties=Array.from(new Set(scope.map(r=>r.party))).sort();const statuses=Array.from(new Set(scope.map(r=>r.status))).sort();
 const shown=scope.filter(r=>(!party||r.party===party)&&(!status||r.status===status)&&(!search||`${r.name} ${r.fullName} ${r.party} ${r.number}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(search.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())));
 const counts:Record<string,number>={};records.filter(r=>r.offices.includes(office)).forEach(r=>counts[r.uf]=(counts[r.uf]||0)+1);const nationalCount=nationalRecords.filter(r=>r.uf==='BR'&&r.offices.includes(office)).length;const max=Math.max(1,...Object.entries(counts).filter(([k])=>k!=='BR').map(([,v])=>v));
 return <section className="panel map-panel"><div className="panel-heading"><div><h2>{showMap?'Mapa eleitoral dos estados':'Candidatos e partidos'} <span className="count-tag">{year}</span></h2><p>{showMap?'Pesquisas registradas e candidaturas oficiais por UF':'Cadastro oficial de Presidente e Governador · TSE'}</p></div><div className="office-switch" aria-label="Cargo no mapa">{['Presidente','Governador'].map(o=><button key={o} aria-pressed={office===o} className={office===o?'selected':''} onClick={()=>{onOffice(o);setParty('');setStatus('');setLimit(12)}}>{o}</button>)}</div></div>
 <div className={showMap?'map-layout':'candidate-only'}>{showMap&&<div className="map-canvas"><div className="map-summary"><span><MapPin size={16}/>{uf&&uf!=='BR'?uf:'Todos os estados'}</span>{uf&&<button className="text-button" onClick={()=>onUf('')}>Limpar estado</button>}</div>{mapError?<div className="error">{mapError}</div>:<svg className="brazil-map" viewBox="0 0 570 550" role="group" aria-label="Mapa dos estados brasileiros: quantidade de pesquisas registradas">{features.map(f=>{const code=codes[f.properties.codarea],count=counts[code]||0;return <path key={code} d={path(f.geometry)} fill={uf===code?'#126650':count?`hsl(160 48% ${88-count/max*42}%)`:'#edf1f4'} stroke={uf===code?'#073c31':'white'} strokeWidth={uf===code?2.5:1.4} fillRule="evenodd" role="button" tabIndex={0} aria-label={`${code}: ${count} pesquisas de ${office}. Filtrar estado.`} aria-pressed={uf===code} onClick={()=>onUf(uf===code?'':code)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onUf(uf===code?'':code)}}} onMouseEnter={()=>setHover(code)} onMouseLeave={()=>setHover('')} onFocus={()=>setHover(code)} onBlur={()=>setHover('')}><title>{code}: {count} pesquisas registradas</title></path>})}{features.map(f=>{const code=codes[f.properties.codarea];if(!centers[code])return null;const [x,y]=project(centers[code]);return <text key={code} x={x} y={y} textAnchor="middle" fill={uf===code?'white':'#294f4a'} fontSize="11" fontWeight="650" pointerEvents="none">{code}</text>})}</svg>}<div className="map-legend"><span>Menos registros</span><i/><span>Mais registros</span></div><div className="map-hover" aria-live="polite">{hover?`${hover} · ${counts[hover]||0} pesquisas de ${office}`:'Clique em um estado para consultar o recorte'}</div>{office==='Presidente'&&<div className="national-note"><strong>{nationalCount}</strong><span>pesquisas nacionais deste cargo no ano, antes dos outros filtros. Não são distribuídas artificialmente entre estados.</span></div>}<small className="map-source">Malha territorial: IBGE · Cor = quantidade de pesquisas, não intenção de voto.</small></div>}
 <div className="candidate-area"><div className="candidate-heading"><Users size={18}/><h3>{office==='Presidente'?'Candidaturas à Presidência':`Candidaturas ao governo${uf&&uf!=='BR'?` · ${uf}`:''}`}</h3></div><div className="candidate-filters"><label className="field"><span>Partido</span><select value={party} onChange={e=>{setParty(e.target.value);setLimit(12)}}><option value="">Todos</option>{parties.map(p=><option key={p}>{p}</option>)}</select></label><label className="field"><span>Turno do cadastro</span><select value={turn} onChange={e=>{setTurn(e.target.value);setParty('');setStatus('');setLimit(12)}}><option value="1">1º turno</option><option value="2">2º turno</option></select></label><label className="field"><span>Situação no TSE</span><select value={status} onChange={e=>{setStatus(e.target.value);setLimit(12)}}><option value="">Todas</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="candidate-search search"><Search size={15}/><input aria-label="Buscar candidato" value={search} onChange={e=>{setSearch(e.target.value);setLimit(12)}} placeholder="Nome, partido ou número"/></label></div><p className="candidate-count">{busy?'Carregando candidatos…':`${shown.length} candidaturas encontradas`}</p>{error&&<div className="error">{error}</div>}{![2026,2022,2018,2014].includes(year)?<p className="candidate-info">Selecione 2026, 2022, 2018 ou 2014 para consultar as eleições de Presidente e Governador.</p>:<><div className="candidate-list">{shown.slice(0,limit).map(c=><article className="candidate-row" key={c.id}><span className="candidate-number">{c.number}</span><div><strong>{c.name}</strong><span>{c.party} · {c.office==='Presidente'?'Brasil':c.uf}</span><small>{c.status}</small><details><summary>Dados da candidatura</summary><p>{c.fullName}<br/>{c.partyName}<br/>{c.election}<br/>Coligação: {c.coalition}<br/>{c.composition}</p></details></div></article>)}</div>{!busy&&!shown.length&&<p className="candidate-info">Nenhuma candidatura neste recorte do cadastro oficial.</p>}{shown.length>limit&&<button className="button show-more" onClick={()=>setLimit(n=>n+24)}>Mostrar mais candidatos</button>}</>}<div className="candidate-warning"><Info size={16}/><span>Partido, nome, turno e situação filtram o cadastro de candidaturas. Não comprovam participação em uma pesquisa nem alteram a contagem no mapa.</span></div><div className="candidate-source">{generated&&<span>Extração TSE: {generated}</span>}<a href={`https://dadosabertos.tse.jus.br/dataset/candidatos-${year}`} target="_blank" rel="noreferrer">Fonte dos candidatos <ExternalLink size={12}/></a></div></div></div></section>
}
