import { createInflateRaw } from 'node:zlib';
import { Readable } from 'node:stream';
export const YEARS = [2026,2024,2022,2020,2018,2016,2014,2012];
export type Poll = {id:string;year:number;uf:string;city:string;ue:string;election:string;institute:string;company:string;cnpj:string;offices:string[];registered:string;start:string;end:string;release:string;sample:number;cost:number;own:boolean|null;statistician:string;conre:string;detailFile?:string};
export function normalize(r:Record<string,string>):Poll {return {id:r.NR_PROTOCOLO_REGISTRO,year:+r.AA_ELEICAO,uf:r.SG_UF,ue:r.SG_UE,city:r.SG_UE?.length>2?r.NM_UE:'',election:r.NM_ELEICAO,institute:r.NM_EMPRESA_FANTASIA&&r.NM_EMPRESA_FANTASIA!=='#NULO#'?r.NM_EMPRESA_FANTASIA:r.NM_EMPRESA,company:r.NM_EMPRESA,cnpj:r.NR_CNPJ_EMPRESA,offices:(r.DS_CARGO||'').split(',').map(s=>s.trim()).filter(s=>s&&s!=='#NULO#'),registered:r.DT_REGISTRO?.slice(0,10),start:r.DT_INICIO_PESQUISA?.slice(0,10),end:r.DT_FIM_PESQUISA?.slice(0,10),release:r.DT_DIVULGACAO?.slice(0,10)||'',sample:+r.QT_ENTREVISTADO,cost:Number(r.VR_PESQUISA?.replace(',','.')),own:r.ST_PESQUISA_PROPRIA==='S',statistician:r.NM_ESTATISTICO_RESP,conre:r.CD_CONRE};}
// Stateful RFC-4180 parser: quoted semicolons, escaped quotes and multiline fields.
export class CsvParser { field=''; row:string[]=[]; quoted=false; afterQuote=false; onRow:(row:string[])=>void; constructor(onRow:(r:string[])=>void){this.onRow=onRow} push(s:string){for(const c of s){if(this.afterQuote){if(c==='"'){this.field+='"';this.afterQuote=false;continue}this.quoted=false;this.afterQuote=false}if(this.quoted){if(c==='"')this.afterQuote=true;else this.field+=c;continue}if(c==='"'&&!this.field){this.quoted=true;continue}if(c===';'){this.row.push(this.field);this.field=''}else if(c==='\n'){this.row.push(this.field.replace(/\r$/,''));this.onRow(this.row);this.row=[];this.field=''}else if(c!=='\r')this.field+=c}} end(){if(this.field||this.row.length){this.row.push(this.field);this.onRow(this.row)}}}
async function official(url:string){const u=new URL(url);if(!['dadosabertos.tse.jus.br','cdn.tse.jus.br'].includes(u.hostname)||u.protocol!=='https:')throw Error('Fonte fora do domínio oficial.');const res=await fetch(url,{signal:AbortSignal.timeout(55000)});if(!res.ok)throw Error(`O TSE respondeu ${res.status}.`);return res}
export async function catalog(year:number){const d:any=await(await official(`https://dadosabertos.tse.jus.br/api/3/action/package_show?id=pesquisas-eleitorais-${year}`)).json();if(!d.success)throw Error('Catálogo indisponível');return d.result}
const cache=new Map<number,{time:number;data:any}>();
export async function loadPolls(year:number, detail?:string){const hit=cache.get(year);if(!detail&&hit&&Date.now()-hit.time<15*60000)return hit.data;const meta=await catalog(year);const resource=meta.resources.find((r:any)=>r.name?.toLowerCase()==='pesquisas eleitorais');if(!resource)throw Error('Arquivo de pesquisas não encontrado no catálogo.');const response=await official(resource.url);const chunks:Uint8Array[]=[];let size=0;const reader=response.body!.getReader();while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>48*1024*1024){await reader.cancel();throw Error('Arquivo excede o limite desta consulta. Acesse o download oficial.')}chunks.push(r.value)}const buf=Buffer.concat(chunks);chunks.length=0;
let end=buf.length-22;while(end>=Math.max(0,buf.length-65557)&&buf.readUInt32LE(end)!==0x06054b50)end--;if(end<0)throw Error('Arquivo ZIP inválido');let pos=buf.readUInt32LE(end+16);let compressed:Buffer|undefined;let method=0;
while(pos<end&&buf.readUInt32LE(pos)===0x02014b50){const nameLen=buf.readUInt16LE(pos+28),extra=buf.readUInt16LE(pos+30),comment=buf.readUInt16LE(pos+32);const name=buf.subarray(pos+46,pos+46+nameLen).toString();if(/_BRASIL\.csv$/i.test(name)){const local=buf.readUInt32LE(pos+42),start=local+30+buf.readUInt16LE(local+26)+buf.readUInt16LE(local+28);compressed=buf.subarray(start,start+buf.readUInt32LE(pos+20));method=buf.readUInt16LE(pos+10);break}pos+=46+nameLen+extra+comment}if(!compressed)throw Error('CSV nacional não localizado.');
let headers:string[]|undefined;let generated='';let found:Record<string,string>|undefined;const records:Poll[]=[];const ids=new Set<string>();const parser=new CsvParser(row=>{if(!headers){headers=row;return}const r=Object.fromEntries(headers.map((k,i)=>[k,row[i]||'']));if(!r.NR_PROTOCOLO_REGISTRO)return;generated=`${r.DT_GERACAO} ${r.HH_GERACAO}`;if(detail){if(r.NR_PROTOCOLO_REGISTRO===detail)found=r}else if(!ids.has(r.NR_PROTOCOLO_REGISTRO)){ids.add(r.NR_PROTOCOLO_REGISTRO);records.push(normalize(r))}});const stream=method===8?Readable.from([compressed]).pipe(createInflateRaw()):Readable.from([compressed]);const decoder=new TextDecoder('windows-1252');for await(const chunk of stream)parser.push(decoder.decode(chunk,{stream:true}));parser.push(decoder.decode());parser.end();if(detail){if(!found)throw Error('Registro não encontrado.');return {record:found}}const data={records,generated,fetchedAt:new Date().toISOString(),source:resource.url,mode:'live'};cache.clear();cache.set(year,{time:Date.now(),data});return data}
